### ISSUE TITLE
CAMB transfer function

### ISSUE THREAD

**Issue by andrejdvornik** [joezuntz/cosmosis-standard-library#116]
Not an issue per se, but more of a polite feature request.

For the KiDS efforts we are building the halo model within the CosmoSIS framework and are using `hmf` package for a backbone of a couple of modules to get flexibility of trying out different halo mass functions, halo bias functions, mass definitions and all that. The issue we have (and something we need to work around a bit) is that `hmf` re-runs the CAMB to get the transfer function, which is used to get the needed ingredients for the resulting halo mass function. This is particularly annoying as not only it slows down the calculations but also treats a couple of parameters differently than what it is done in CAMB implementation in CosmoSIS, resulting in discrepancies between power spectra predictions (but that is solvable, thankfully, but with a lot of redundancy). 

There is a simple work around and that is that `hmf` can read any transfer function, which also results in it not running the CAMB. For that we would need the transfer function exposed to the datablock by the CAMB CosmoSIS module. 

The required quantity is calculated buy CAMB in the following way:

`transfer_func = camb.get_transfer_functions(camb_params).get_matter_transfer_data().transfer_data`, 

which I think should be fairly easy added to the CosmoSIS CAMB interface.

Me, Marika, and Catherine would greatly appreciate help in exposing this quantity, which would greatly simplify the current somewhat patchwork of code to a couple of lines, and allow for a consistent interaction between two modules.

**Comment by andrejdvornik** [comment]
The raw implementation is done and I have opened a pull request, but I am 100% sure we need to iterate on the exact implementation.

**Comment by joezuntz** [comment]
Hi Andrej - thanks for putting this in - I will have a look!

**Comment by andrejdvornik** [comment]
I realised I need to add the additions to the yaml file, will do this in the next couple of days.

**Comment by andrejdvornik** [comment]
Updated yaml file in PR #126, closing the issue as the functionality has been implemented for a long time.
