### ISSUE TITLE
wrong lapack link in 'setup-cosmosis3' on nersc

### ISSUE THREAD

**Issue by sujeong-lee** [joezuntz/cosmosis-standard-library#128]
Hi, it seems there was a bug in the LAPACK_LINK setting in `/dvs_ro/cfs/projectdirs/des/zuntz/cosmosis-global/setup-cosmosis3` while following the instructions for NERSC installation.

With the help of @marcpaterno, I set `export LAPACK_LINK="-L${CONDA_PREFIX}/lib -llapack"`, and now it seems to be working fine.

**Comment by joezuntz** [comment]
Thanks for this - I'm back from leave now and have fixed it in the shared version.
