### ISSUE TITLE
Running Pantheon with class

### ISSUE THREAD

**Issue by Uendert** [joezuntz/cosmosis-standard-library#23]
Dear all,

I am simply trying the pantheon.ini example, but rather using class. I believe I had made the relevant changes, but I still got an error that I couldn't trace back:

`Running class ...
(Could not get a likelihood) Error:name 'warnings' is not defined
`

I am attaching the `pantheon_class.ini` and `pantheon_values.ini` files.

Any help would be much appreciated :)

[pantheon_.zip](https://github.com/joezuntz/cosmosis-standard-library/files/9275900/pantheon_.zip)

Thanks,
-- Uendert

**Comment by joezuntz** [comment]
Also - the warning it was trying to give you was about the names of neutrino parameters. Do pay attention to those warnings when they appear!

**Comment by joezuntz** [comment]
Closing this as I think it is dealt with, but please re-open if needed.
