### ISSUE TITLE
'SpectrumCalculator' object has no attribute 'save_kernels'

### ISSUE THREAD

**Issue by mr-superonion** [joezuntz/cosmosis-standard-library#30]
It seems that the self.save_kernels() function is missing in the class!

https://github.com/joezuntz/cosmosis-standard-library/blob/d9567095ca27ba027832de6327abc36516cee8e9/structure/projection/project_2d.py#L1632

**Comment by joezuntz** [comment]
Thanks for spotting this! 

I think I planned to remove this option, but I don't remember why and it is useful, so I will put it back in.

**Comment by joezuntz** [comment]
This fix is now merged to the main branch - I've added `save_kernels=T` to save everything as n(chi), W(chi) values.
