### ISSUE TITLE
Redshift of the logPkRatio is not in increasing order

### ISSUE THREAD

**Issue by mr-superonion** [joezuntz/cosmosis-standard-library#31]
https://github.com/joezuntz/cosmosis-standard-library/blob/a689986c1c6241fc1ecdbc37cc9c95f0f4cb3876/structure/baryon_power_scaling/data/logPkRatio_TNG100.dat#L1

I guess the column `z007` below should come after z018? 
Or could there be a typo and the column actually is `z070`?
```
z104 z007 z035 z018 
```
Now the pipeline comes to an error message if this P(k) ratio is used for rescaling.
```
file=${COSMOSIS_SRC_DIR}/structure/baryon_power_scaling/baryonic_interface.py
ratio_table=${COSMOSIS_SRC_DIR}/structure/baryon_power_scaling/data/logPkRatio_cowls_AGN_Mseed800_T8.5_WMAP7_L100N512.dat
```

The error massage is copied as follow (y refers to the redshift, I guess):
```
  File "/work/xiangchong.li/cosmosis2-mpich/cosmosis-standard-library/structure/baryon_power_scaling/baryonic.py", line 62, in __init__
    self.ratio = scipy.interpolate.RectBivariateSpline(logk, redshifts, logpkratio)
  File "/work/xiangchong.li/miniconda3/envs/cosmosis2-mpich/lib/python3.9/site-packages/scipy/interpolate/_fitpack2.py", line 1409, in __init__
    raise ValueError('y must be strictly increasing')
ValueError: y must be strictly increasing

```

**Comment by joezuntz** [comment]
This is interesting.  It seems to be an error in the original data file, which is here:
https://github.com/hungjinh/baryon-power-spectra/blob/master/logPkRatio/logPkRatio_TNG100.dat

I will ask the author about it.

**Comment by mr-superonion** [comment]
Thanks for finding the original data file. I guess it is better to put a link to the original repo in the module description.

Hmm.. The README file (line 52) in the linked repo says that redshift column is 0.7 :
https://github.com/hungjinh/baryon-power-spectra/blob/c493f5233cead682e8a28948b355ed8bb9645329/logPkRatio/README#L52

**Comment by mr-superonion** [comment]
BTW, it seems that [this directory](https://github.com/joezuntz/cosmosis-standard-library/tree/main/structure/owls) can be included into this module as they seems to be the same function.

**Comment by joezuntz** [comment]
I've heard back from Hung-Jin - this is an error in the header as you thought:
https://github.com/hungjinh/baryon-power-spectra/commit/a673f3457a3f70e3730df3d59f891004780484b1

Fix is here: https://github.com/joezuntz/cosmosis-standard-library/pull/34 
will merge once tests complete.

**Comment by joezuntz** [comment]
Fix for this is merged - thanks for reporting!
