### ISSUE TITLE
fsigma8 is sigma8 in boltzmann/class module

### ISSUE THREAD

**Issue by adematti** [joezuntz/cosmosis-standard-library#41]
Hi,
Typo is here: https://github.com/joezuntz/cosmosis-standard-library/blob/df7c5434d5ce57c36f9a09a422e35cff65cc88e8/boltzmann/class/class_interface.py#L175
`np.array(sigma_8_z)` should be `np.array(fsigma8)`, I guess.
Thanks!

**Comment by joezuntz** [comment]
Thanks so much for spotting this!
Testing a fix now.
