### ISSUE TITLE
Newer version of class (v>2.7)

### ISSUE THREAD

**Issue by SebastianBocquet** [joezuntz/cosmosis-standard-library#8]
Hi! I am working with some folks who have interesting modifications of class v>2.7. It would be great if newer version of class were supported by cosmosis-standard-library so we would struggle less with running the modified class code.

**Comment by joezuntz** [comment]
I've made a pull request which bundles version 3.2.0, as well as making some other improvements.  If the tests pass, could you have a look and see if it works for you, @SebastianBocquet ?

**Comment by joezuntz** [comment]
I added `examples/planck_class.ini` in the new branch as an illustration.

**Comment by SebastianBocquet** [comment]
This looks great, thank you! I won't be able to test with the modified class code myself, but I was told that this should work with v3.2.0.

**Comment by SebastianBocquet** [comment]
FYI the modification of class we're interested in works with the new interface so this is very helpful!
