### ISSUE TITLE
Consistency module docs confusing.

### ISSUE THREAD

**Issue by itrharrison** [joezuntz/cosmosis-standard-library#90]
It took me a few goes to be able to use the `relations_file` option in the consistency module.

This was partially because the docs do not specify how the alternative parameter relations file should look, and copy and pasting what is currently in the docs includes whitespace, which then doesn't read in properly.

I wanted to add a relation which is solely a rename, using the form:
`omega_cdm=omega_c`

Happy to do a quick PR which either
a) Updates the docs to include more explicit specification of the relations file
b) Also updates the code to allow for renames. Probably something like
```
        if extra_relations:
            relations = relations + EXTRA_RELATIONS
```
at https://github.com/joezuntz/cosmosis-standard-library/blob/7e65feb2f29c0eaff5acff80826489a4549def63/utility/consistency/consistency.py#L55 and an extra module argument to specify an extra relations file.

If there is a better way of implementing these renames happy to do that too!

**Comment by joezuntz** [comment]
Thanks - both these would be really useful!
