### ISSUE TITLE
Correct mapping between H0 and cosmomc_theta unclear

### ISSUE THREAD

**Issue by itrharrison** [joezuntz/cosmosis-standard-library#93]
Currently if `cosmomc_theta` is set as a sampling parameter then the consistency module calculates an H0 for this value using https://github.com/joezuntz/cosmosis-standard-library/blob/main/utility/consistency/theta_h0.py

In the camb interface the `if` statement is written such that the `cosmomc_theta` is never given directly to camb, only the H0 which has been calculated by consistency:
https://github.com/joezuntz/cosmosis-standard-library/blob/c781073b81a5d31b62186a5f782c018061b8e4bf/boltzmann/camb/camb_interface.py#L352
you know it doesn't because it also would include an erroneous factor of 100!

This means that if `theta_H0_range` is specified as a camb argument (as for the ACT DR6 lensing likelihood) then it gets ignored as camb never receives a `cosmomc_theta`.

Reversing the the order of the `if` in the camb interface means that `cosmomc_theta` is used, but then a problem occurs with the value for H0 calculated by camb directly being different to the one calculated by consistency, and complaints ensue.

![theta_H0](https://github.com/joezuntz/cosmosis-standard-library/assets/3586409/43701e5a-6ae7-4751-a726-f35b998a235c)

I compared the approximation in consistency https://github.com/joezuntz/cosmosis-standard-library/blob/c781073b81a5d31b62186a5f782c018061b8e4bf/utility/consistency/theta_h0.py#L46 to the one in camb https://github.com/cmbant/CAMB/blob/648a52d32b2c30295d874d62209a42040ffbb121/fortran/results.f90#L906 and made a small tweak to omdmh2 but it doesn't change things much.

You can replicate this by running `cosmosis examples/act-dr6-lens.ini` and `python debug_output/h0_theta_plot.py` whilst on this branch: https://github.com/itrharrison/cosmosis-standard-library-itrharrison/tree/dev-thetamcfix which also spits out all the parameter values (which look consistent) to file.

**Comment by joezuntz** [comment]
When I do this directly in a notebook instead of going through the modules I get much better results for the camb side - see attached.  This could either be an issue with re-using the CambParams object somehow in your tests, or with the other cosmo params that are set in the camb interface module. I'll try both those now.

**Comment by joezuntz** [comment]
I get the same results when using the modules in full.  So I think this must be related to re-using the camb params objects.

There is a significant difference when Omega_nu != 0, which I'll look into now.

[theta_h0_comparison_v2.pdf](https://github.com/joezuntz/cosmosis-standard-library/files/12369132/theta_h0_comparison_v2.pdf)

**Comment by joezuntz** [comment]
There's also a problem with the factor of 100, which is included in the camb module but not the consistency one.

**Comment by joezuntz** [comment]
I think this is dealt with fully now - we use camb to do the conversion.
