### ISSUE TITLE
saving nbin_a and nbin_b for shear_cl_gg section

### ISSUE THREAD

**Issue by mr-superonion** [joezuntz/cosmosis-standard-library#95]
Hello @joezuntz ,

Thanks for your time reading this issue.

Do you think it is a good idea to put the following lines below [this line](https://github.com/joezuntz/cosmosis-standard-library/blob/c781073b81a5d31b62186a5f782c018061b8e4bf/shear/add_intrinsic/add_intrinsic.py#L81)?
```
block[shear_shear_gg, "nbin_a"] = block[shear_shear, "nbin_a"]
block[shear_shear_gg, "nbin_b"] = block[shear_shear, "nbin_b"]
block[shear_shear_gg, "nbin"] = block[shear_shear, "nbin"]
block[shear_shear_gg, "sample_a"] = block[shear_shear, "sample_a"]
block[shear_shear_gg, "sample_b"] = block[shear_shear, "sample_b"]
block[shear_shear_gg, "is_auto"] = block[shear_shear, "is_auto"]
block[shear_shear_gg, "auto_only"] = block[shear_shear, "auto_only"]
block[shear_shear_gg, "sep_name"] = block[shear_shear, "sep_name"]
```
Then it is possible to use cosmosis to perform Hankel transforms on `shear_shear_gg`.
Maybe just `nbin_a` and `nbin_b` are enough..

**Comment by joezuntz** [comment]
Thanks @mr-superonion  - that's a good idea.  I'll put that in.

**Comment by joezuntz** [comment]
Done!
